# Site settings
title: raycp's blog, just fun
url: "http://ray-cp.github.io"    # the protocol and hostname of your site, eg. `http://xxxx.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  SOMETHING MESSED.

# Your information
email: raycp@protonmail.com
author: raycp
avatar: "http://s.gravatar.com/avatar/a1ab0d9de11daf93ca2637bd680c5638?s=80"
profile: DON'T STOP UNTIL YOU'RE PROUD.
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx   #get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

#baidu-analysis: 23e2fba4a9ee47e00000d658a6f021db
